let stages = [], currentUser = null, isRegister = false;
const body = document.querySelector("#stages-body"), dialog = document.querySelector("#stage-dialog"), form = document.querySelector("#stage-form"), dateFormat = new Intl.DateTimeFormat("fr-FR");
const api = async (path, options = {}) => { const response = await fetch(path, { credentials:"same-origin", headers:{"Content-Type":"application/json", ...(options.headers || {})}, ...options }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error || "Une erreur est survenue."); return data; };
const addMonths = (dateString, months) => { const d = new Date(`${dateString}T12:00:00`); d.setMonth(d.getMonth() + months); return d; };
const showDate = date => dateFormat.format(date instanceof Date ? date : new Date(`${date}T12:00:00`));
const showMonth = date => { const value = date instanceof Date ? date : new Date(`${date}T12:00:00`); return `${String(value.getMonth() + 1).padStart(2, "0")}/${value.getFullYear()}`; };
const badgeClass = status => ({"Terminé":"termine","Pas payé":"non-paye","Pas commencé":"pas-commence","En cours":"en-cours","En cours de paiement":"paiement"}[status] || "");
const escapeHtml = value => { const node = document.createElement("div"); node.textContent = value; return node.innerHTML; };
async function loadStages() { stages = await api("/api/stages"); render(); }
function updateMetrics() { const count = value => stages.filter(stage => stage.status === value).length; document.querySelector("#count-current").textContent=count("En cours de paiement"); document.querySelector("#count-finished").textContent=count("Terminé"); document.querySelector("#count-not-started").textContent=count("Pas commencé"); document.querySelector("#count-unpaid").textContent=count("Pas payé"); }
function render() { const term=document.querySelector("#search").value.trim().toLowerCase(), filter=document.querySelector("#filter-status").value; const displayed=stages.filter(s=>s.name.toLowerCase().includes(term)&&(!filter||s.status===filter)); body.innerHTML=displayed.map(s=>`<tr><td class="stage-name">${escapeHtml(s.name)}</td><td><span class="badge ${badgeClass(s.status)}">${escapeHtml(s.status)}</span></td><td class="date">${showDate(s.start)}</td><td class="date">${showDate(s.end)}</td><td class="date">${showMonth(addMonths(s.start,1))}</td><td class="date">${showMonth(addMonths(s.start,7))}</td><td class="notes">${escapeHtml(s.notes||"—")}</td><td><div class="row-actions"><button class="small-button" data-edit="${s.id}">Modifier</button><button class="small-button danger" data-delete="${s.id}">Supprimer</button></div></td></tr>`).join(""); document.querySelector("#empty-state").hidden=displayed.length!==0; updateMetrics(); }
function openForm(stage) { form.reset(); document.querySelector("#import-status").textContent=""; document.querySelector("#stage-id").value=stage?.id||""; document.querySelector("#dialog-title").textContent=stage?"Modifier le stage":"Ajouter un stage"; if(stage) for(const [key,id] of [["name","stage-name"],["status","stage-status"],["start","stage-start"],["end","stage-end"],["notes","stage-notes"]]) document.querySelector(`#${id}`).value=stage[key]; dialog.showModal(); }
function showApp(user) { currentUser=user; document.querySelector("#current-user").textContent=user.email; document.querySelector("#auth-screen").hidden=true; document.querySelector("#app-screen").hidden=false; loadStages().catch(() => { body.innerHTML=""; document.querySelector("#empty-state").hidden=false; }); }
async function session() { try { showApp(await api("/api/me")); } catch { document.querySelector("#auth-screen").hidden=false; document.querySelector("#app-screen").hidden=true; } }
document.querySelector("#auth-form").addEventListener("submit",async e=>{e.preventDefault();const status=document.querySelector("#auth-status"),button=document.querySelector("#auth-submit");status.className="import-status";status.textContent="Connexion…";button.disabled=true;try{showApp(await api(isRegister?"/api/register":"/api/login",{method:"POST",body:JSON.stringify({email:document.querySelector("#auth-email").value,password:document.querySelector("#auth-password").value})}));}catch(error){status.className="import-status error";status.textContent=error.message;}finally{button.disabled=false;}});
document.querySelector("#auth-toggle").addEventListener("click",()=>{isRegister=!isRegister;document.querySelector("#auth-title").textContent=isRegister?"Créer mon compte":"Suivi de mes stages";document.querySelector("#auth-description").textContent=isRegister?"Renseigne ton e-mail et choisis un mot de passe d’au moins 8 caractères.":"Connecte-toi pour retrouver ton suivi personnel.";document.querySelector("#auth-submit").textContent=isRegister?"Créer mon compte":"Se connecter";document.querySelector("#auth-toggle").textContent=isRegister?"J’ai déjà un compte":"Je n’ai pas encore de compte";document.querySelector("#auth-status").textContent="";});
document.querySelector("#logout").addEventListener("click",async()=>{await api("/api/logout",{method:"POST"});currentUser=null;session();}); document.querySelector("#add-stage").addEventListener("click",()=>openForm()); document.querySelector("#close-dialog").addEventListener("click",()=>dialog.close());document.querySelector("#cancel-dialog").addEventListener("click",()=>dialog.close());document.querySelector("#search").addEventListener("input",render);document.querySelector("#filter-status").addEventListener("change",render);
body.addEventListener("click",async e=>{const id=e.target.dataset.edit||e.target.dataset.delete;if(!id)return;if(e.target.dataset.edit)openForm(stages.find(s=>String(s.id)===id));if(e.target.dataset.delete&&confirm("Supprimer ce stage ?")){await api(`/api/stages/${id}`,{method:"DELETE"});await loadStages();}});
document.querySelector("#stage-pdf").addEventListener("change",async e=>{const file=e.target.files[0];if(!file)return;const message=document.querySelector("#import-status");message.textContent="Lecture du PDF…";try{const data=new FormData();data.append("pdf",file);const r=await fetch("/api/extract-pdf",{method:"POST",body:data});const x=await r.json();if(!r.ok)throw new Error(x.error);for(const [key,id]of[["name","stage-name"],["start","stage-start"],["end","stage-end"],["notes","stage-notes"]])document.querySelector(`#${id}`).value=x[key]||"";message.className="import-status success";message.textContent="PDF lu : vérifie puis enregistre.";}catch(error){message.className="import-status error";message.textContent=error.message;}});
form.addEventListener("submit",async e=>{e.preventDefault();const id=document.querySelector("#stage-id").value;const stage={name:document.querySelector("#stage-name").value.trim(),status:document.querySelector("#stage-status").value,start:document.querySelector("#stage-start").value,end:document.querySelector("#stage-end").value,notes:document.querySelector("#stage-notes").value.trim()};if(stage.end<stage.start)return alert("La date de fin doit être postérieure au début.");await api(id?`/api/stages/${id}`:"/api/stages",{method:id?"PUT":"POST",body:JSON.stringify(stage)});dialog.close();await loadStages();}); session();
